image:
  file: .gitpod.Dockerfile
tasks:
  - name: Android Appetize info
    command: |
      curl -sS --http1.1 "https://$APPETIZE_API_TOKEN@api.appetize.io/v1/apps/$APPETIZE_PUBLICKEY" \
          -F "file=@/workspace/oblique-strategies/build/app/outputs/flutter-apk/app.apk" \
          -F platform=android \
          -F "buttonText=Start App" \
          -F "postSessionButtonText=Start App" \
          > .appetize.json

      APPETIZE_PUBLICKEY=$(jq -r .publicKey .appetize.json)
      gp env "APPETIZE_PUBLICKEY=$APPETIZE_PUBLICKEY"
      export APPETIZE_PUBLICKEY
      gp preview "https://appetize.io/embed/$APPETIZE_PUBLICKEY?device=pixel4&autoplay=true"
  - name: Build for different targets
    init: |
      flutter build -v web
      flutter build -v bundle
      flutter build -v appbundle
      flutter build -v apk
      touch /workspace/.template_init

  - name: Run project
    command: |
      printf "\033[3J\033c\033[3J" && if test ! -e /workspace/.template_init; then {
        printf "Waiting for the flutter build process to complete ..."
        until test -e /workspace/.template_init; do
          sleep 0.5
        done
      } fi
      flutter pub get
      flutter run

ports:
  - port: 5900
    onOpen: ignore
    description: vnc
  - port: 6080
    onOpen: ignore
    description: flutter
  - port: 8080
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 9100-9101
    onOpen: ignore
  - port: 40000-50000
    onOpen: ignore