name: oblique_strategies
description: Over one hundred worthwhile dilemmas
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  google_fonts: ^5.1.0
  flutter_card_swiper: ^6.0.0
  get_storage: ^2.1.1
  ionicons: ^0.2.2
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#000000"

assets:
  - assets/fonts/