name: oblique_strategies
description: Over one hundred worthwhile dilemmas
publish_to: 'none'

version: 0.1.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  flutter_card_swiper: ^7.0.1
  get_storage: ^2.1.1
  ionicons: ^0.2.2
  flip_card: ^0.7.0
  flutter_local_notifications: ^17.1.2
  workmanager: ^0.5.2
  timezone: ^0.9.2
  flutter_localization: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  fonts:
    - family: Univers
      fonts:
        - asset: assets/fonts/Univers-Regular.ttf
        - asset: assets/fonts/Univers-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon_square.png"
  image_path_ios: "assets/icon/icon_square.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon_square.png"
    background_color: "#000000"
    theme_color: "#000000"

assets:
  - assets/fonts/
