name: oblique_strategies
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  google_fonts: ^5.1.0
  flutter_card_swiper: ^6.0.0
  get_storage: ^2.1.1
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - fonts/